######################################################################
# Automatically generated by qmake (3.0) Fri Sep 9 03:48:41 2016
######################################################################

TEMPLATE = app
TARGET = state_util
INCLUDEPATH += .
QT += network

# Input
SOURCES += state_test.cpp
